# Translation mapping used in the notebook for lockers/wearers reference extract (Polish -> English)
LOCWEA_TRANS_REF = {
    "Kod kontrahenta": "Customer Code",
    "Kontrahent": "Customer",
    "Kod oddzia?u": "Department Code",
    "Oddzia?": "Department",
    "Kod pracownika": "Employee Code_Ref",
    "Pracownik": "Employee_Ref",
    "Szatnia": "Locker Room",
    "Szafka": "Locker",
    "Skrytka": "Safe/Compartment",
    "Kod asortymentu": "Item Code",
    "Asortyment": "Item",
    "Rozmiar": "Size",
    "Kod kreskowy": "Barcode",
    "Kod obcy": "External Code",
    "UID": "HF Tag",
    "Ostatni ruch": "Last Movement",
    "Data ostatniego ruchu": "Date of Last Movement",
    "Ilo?? pra?": "Number of Washes",
    "Data ostatniego prania": "Date of Last Wash",
    "ID Kontrahenta": "CustomerID",
    "ID Oddzia?u": "DepartmentID_Ref",
    "ID Pracownika": "EmployeeID_Ref",
}
